blank_issues_enabled: false
contact_links:
  - name: 🤗 Get help
    url: https://github.com/khulnasoft/readyapi/discussions/new?category=q-a
    about: If you can’t get something to work the way you expect, open a question in our discussion forums.
  - name: 💡 Feature request
    url: https://github.com/khulnasoft/readyapi/discussions/new?category=ideas
    about: Suggest any ideas you have using our discussion forums.
  - name: 💬 Chat with us
    url: https://discord.gg/khulnasoft
    about: Suggest any ideas you have using our discussion forums.